### ISSUE TITLE
[EPIC] Winter break R&D

### ISSUE THREAD

**Issue by EliotJanvier** [celte-team/celte-system#74]
A lot of things have already been implemented and we are starting to get a better idea of what works well and what doesn't. 
We should take some time to investigate the weak points of the current stack and research how to improve them, or alternative technologies. 

Points of reflection:

- [x] kafka (is it dynamic enough for what we want, in the end?) check Apache Pulsar (#75 )
- [x] grapes + chunk (is there a better way to split the data) (#86 )
- [x] connection procedure (can we simplify it)
- [x] logs + error handling (pretty much nothing done on this side besides the prometheus stack)

**Comment by ClementToni** [comment]
I was also thinking about the utility of spending some time to re-learn K8s and implement a cluster system that will be needed for the future.
