### ISSUE TITLE
[EPIC] Integrate Kubernetes

### ISSUE THREAD

**Issue by ClementToni** [celte-team/celte-system#94]
To use the dynamic aspect of server meshing, we need a flexible service to scale containers up or down based on our requirements. The goals are:
- [x] _SN (server node)_: Up a new server if the others are overwhelmed, or DOWN it if it is underutilized.
- [x] _Health Check_: Check if SN is responding every ~1sec and down the container if no
- [x] _Master Instances_: Put statically 2 instances of master and check the heartbeat to UP a new one if a crash appears.
- [x] _GUI_: Find a GUI to see the state of every machine.  

Resources: 
[horizontal-pod-autoscale](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
[configure-liveness-readiness-startup](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
[operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/)

**Comment by TheoPAWELEC** [comment]
Clement qui va finir avec un doctorat en Kubernetes
